name: Run Docker Proxy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 290
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Docker
        run: |
          docker build -t telegram-proxy .
          docker run -d --name proxy-container telegram-proxy
          
          # Wait for logs to generate the claim code
          echo "Waiting for playit to generate claim code..."
          sleep 10
          docker logs proxy-container
          
