name: Run Telegram Proxy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'
  push:
    branches:
      - main

jobs:
  run-proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 290
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Start SOCKS5 Proxy
        run: |
          sudo apt-get update
          sudo apt-get install -y microsocks
          
          microsocks -p 10000 &
          sleep 3
          
          # Use 0 to let Serveo automatically assign an available port
          ssh -o StrictHostKeyChecking=no -R 0:localhost:10000 serveo.net
          
